### ISSUE TITLE
Is it possible to highlight code examples in doc comments

### ISSUE THREAD

**Issue by ModProg** [tree-sitter/tree-sitter-rust#130] opened 2022-01-25 10:26 UTC
Not sure about the capabilities of treesitter, but would it be possible to highlight the code in doc comments?
e.g.:
```rs
/// ```rs
/// enum Test {
///
/// }
/// ```
```

**Comment by kellpossible** [comment] 2022-07-12 02:07
If tree-sitter adopts an official markdown parser implementation written in Rust, then this could perhaps be used as an embedded parser in a recursive fashion?

**Comment by SeniorMars** [comment] 2023-02-14 20:42
This would be really cool. Many IDEs are using semantic highlighting for this, but I believe treesitter would be perfect for this.

**Comment by maxcountryman** [comment] 2023-02-14 20:56
I haven't tried this yet, but I stumbled on a technique for highlighting embedded languages in [this video](https://m.youtube.com/watch?v=v3o9YaHBM4Q) that might work here.

**Comment by SeniorMars** [comment] 2023-03-05 04:58
Hacky fix

This works for neovim:

In my `$XDG_CONFIG_HOME/nvim/queries/rust` I have a file called: `injections.scm` with the following:

```query
 ; extends
(
 (line_comment) @_first 
 (_) @rust
 (line_comment) @_last 
 (#match? @_first "^/// ```$") 
 (#match? @_last "^/// ```$")
 (#offset! @rust 0 4 0 4)
)

(
 (line_comment) @_first
 (_) @rust
 (line_comment) @_last
 (#match? @_first "^/// ```rust$")
 (#match? @_last "^/// ```$")
 (#offset! @rust 0 4 0 4)
)
```

Now I get highlights like this:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/31679231/222942467-9dcf6391-6eb4-43f6-a5c0-10e0a890596f.png">


The problem is that this makes neovim very slow, but it's a starting point...

**Comment by amaanq** [comment] 2024-04-07 04:02
out of scope for this *parser*, but this is doable with some post processing via queries/injections or other mechanisms.

**Closed by amaanq** 2024-04-07 04:02 UTC
