### ISSUE TITLE
Doc strings parser

### ISSUE THREAD

**Issue by GrayJack** [tree-sitter/tree-sitter-rust#38] opened 2019-06-11 21:51 UTC
It would be a nice enhancement if doc string comments would be parsed, to provide better highlights when documenting code

**Comment by Luni-4** [comment] 2020-07-22 15:09
@GrayJack 

I think it would be better to differentiate `///` from `//` because they are assigned to the same token

**Comment by GrayJack** [comment] 2020-07-22 15:18
I was talking about in doc comments be able to highlight the code inside the code block, adding a injection point

**Comment by Luni-4** [comment] 2020-07-22 15:23
Oops, sorry, misunderstood the "parser" word used in this issue, I would open another one for my problem then :)

**Comment by GrayJack** [comment] 2020-07-22 17:21
Well, I think we could think on both as the same problem, I have no problem with that

**Comment by Luni-4** [comment] 2020-07-22 19:29
Yep, I agree :)

**Comment by augustocdias** [comment] 2022-01-07 10:42
Maybe if injecting markdown in the `///` blocks since docs in rust are markdown.

**Comment by Chris00** [comment] 2023-12-24 10:46
Duplicate of https://github.com/tree-sitter/tree-sitter-rust/issues/175.

**Closed** 2024-02-16 10:01 UTC
